export const products = [
    {
        id: 1,
        title: 'FLOORING',
        name: 'Premium Marble Slab',
        category: 'A',
        brand: 'Brand 1',
    },
    {
        id: 2,
        title: 'FLOORING',
        name: 'Granite Countertop',
        category: 'A',
        brand: 'Brand 2',
    },
    {
        id: 3,
        title: 'FLOORING',
        name: 'High-Quality Tile Set',
        category: 'A',
        brand: 'Brand 3',
    },
    {
        id: 4,
        title: 'FLOORING',
        name: 'Wooden Floor Panel',
        category: 'A',
        brand: 'Brand 4',
    },
    {
        id: 5,
        title: 'FLOORING',
        name: 'Concrete Wall Panel',
        category: 'B',
        brand: 'Brand 1',
    },
    {
        id: 6,
        title: 'FLOORING',
        name: 'Outdoor Granite Tiles',
        category: 'B',
        brand: 'Brand 2',
    },
    {
        id: 7,
        title: 'FLOORING',
        name: 'Luxury Wooden Deck',
        category: 'B',
        brand: 'Brand 3',
    },
    {
        id: 8,
        title: 'FLOORING',
        name: 'Polished Concrete Slab',
        category: 'B',
        brand: 'Brand 4',
    },
    {
        id: 9,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 1',
    },
    {
        id: 10,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 2',
    },
    {
        id: 11,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 3',
    },
    {
        id: 12,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 4',
    },
    {
        id: 13,
        title: 'FLOORING',
        name: 'Premium Marble Slab',
        category: 'A',
        brand: 'Brand 1',
    },
    {
        id: 14,
        title: 'FLOORING',
        name: 'Granite Countertop',
        category: 'A',
        brand: 'Brand 2',
    },
    {
        id: 15,
        title: 'FLOORING',
        name: 'High-Quality Tile Set',
        category: 'A',
        brand: 'Brand 3',
    },
    {
        id: 16,
        title: 'FLOORING',
        name: 'Wooden Floor Panel',
        category: 'A',
        brand: 'Brand 4',
    },
    {
        id: 17,
        title: 'FLOORING',
        name: 'Concrete Wall Panel',
        category: 'B',
        brand: 'Brand 1',
    },
    {
        id: 18,
        title: 'FLOORING',
        name: 'Outdoor Granite Tiles',
        category: 'B',
        brand: 'Brand 2',
    },
    {
        id: 19,
        title: 'FLOORING',
        name: 'Luxury Wooden Deck',
        category: 'B',
        brand: 'Brand 3',
    },
    {
        id: 20,
        title: 'FLOORING',
        name: 'Polished Concrete Slab',
        category: 'B',
        brand: 'Brand 4',
    },
    {
        id: 21,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 1',
    },
    {
        id: 22,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 2',
    },
    {
        id: 23,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 3',
    },
    {
        id: 24,
        title: 'FLOORING',
        name: 'Modern Marble Counter',
        category: 'C',
        brand: 'Brand 4',
    },
];

export const categories = [
    {
        type: 'A',
        brands: [
            { name: 'Brand 1', count: 342 },
            { name: 'Brand 2', count: 2 },
            { name: 'Brand 3', count: 104 },
            { name: 'Brand 4', count: 72 },
        ],
    },
    {
        type: 'B',
        brands: [
            { name: 'Brand 1', count: 342 },
            { name: 'Brand 2', count: 2 },
            { name: 'Brand 3', count: 104 },
            { name: 'Brand 4', count: 72 },
        ],
    },
    {
        type: 'C',
        brands: [
            { name: 'Brand 1', count: 342 },
            { name: 'Brand 2', count: 2 },
            { name: 'Brand 3', count: 104 },
            { name: 'Brand 4', count: 72 },
        ],
    },
];

export const suppliers = ['Brand 1', 'Brand 2', 'Brand 3', 'Brand 4'];

export const keywords = [
    'Brand 1',
    'Brs',
    'Example 2',
    'Brand Example 2',
    'Brand 2',
];
